<?php
/**
 * CancelInvoice200ResponseTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Mtn\Momo\Collection
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Collection
 *
 * Enable remote collection of bills, fees or taxes
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.9.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Mtn\Momo\Collection\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * CancelInvoice200ResponseTest Class Doc Comment
 *
 * @category    Class
 * @description CancelInvoice200Response
 * @package     Mtn\Momo\Collection
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class CancelInvoice200ResponseTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "CancelInvoice200Response"
     */
    public function testCancelInvoice200Response()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "external_id"
     */
    public function testPropertyExternalId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
