<?php
/**
 * DefaultApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  Mtn\Momo\Collection
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Collection
 *
 * Enable remote collection of bills, fees or taxes
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.9.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Mtn\Momo\Collection\Test\Api;

use \Mtn\Momo\Collection\Configuration;
use \Mtn\Momo\Collection\ApiException;
use \Mtn\Momo\Collection\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * DefaultApiTest Class Doc Comment
 *
 * @category Class
 * @package  Mtn\Momo\Collection
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class DefaultApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for bcAuthorize
     *
     * bc-authorize.
     *
     */
    public function testBcAuthorize()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for cancelInvoice
     *
     * CancelInvoice.
     *
     */
    public function testCancelInvoice()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for cancelPreApproval
     *
     * CancelPreApproval.
     *
     */
    public function testCancelPreApproval()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createAccessToken
     *
     * CreateAccessToken.
     *
     */
    public function testCreateAccessToken()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createInvoice
     *
     * CreateInvoice.
     *
     */
    public function testCreateInvoice()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createOauth2Token
     *
     * CreateOauth2Token.
     *
     */
    public function testCreateOauth2Token()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createPayments
     *
     * CreatePayments.
     *
     */
    public function testCreatePayments()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getAccountBalance
     *
     * GetAccountBalance.
     *
     */
    public function testGetAccountBalance()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getAccountBalanceInSpecificCurrency
     *
     * GetAccountBalanceInSpecificCurrency.
     *
     */
    public function testGetAccountBalanceInSpecificCurrency()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getApprovedPreApprovals
     *
     * GetApprovedPreApprovals.
     *
     */
    public function testGetApprovedPreApprovals()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getBasicUserinfo
     *
     * GetBasicUserinfo.
     *
     */
    public function testGetBasicUserinfo()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getInvoiceStatus
     *
     * GetInvoiceStatus.
     *
     */
    public function testGetInvoiceStatus()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getPaymentStatus
     *
     * GetPaymentStatus.
     *
     */
    public function testGetPaymentStatus()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getPreApprovalStatus
     *
     * GetPreApprovalStatus.
     *
     */
    public function testGetPreApprovalStatus()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getUserInfoWithConsent
     *
     * GetUserInfoWithConsent.
     *
     */
    public function testGetUserInfoWithConsent()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for preApproval
     *
     * PreApproval.
     *
     */
    public function testPreApproval()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for requestToWithdrawTransactionStatus
     *
     * RequestToWithdrawTransactionStatus.
     *
     */
    public function testRequestToWithdrawTransactionStatus()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for requestToWithdrawV1
     *
     * RequestToWithdraw-V1.
     *
     */
    public function testRequestToWithdrawV1()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for requestToWithdrawV2
     *
     * RequestToWithdraw-V2.
     *
     */
    public function testRequestToWithdrawV2()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for requesttoPay
     *
     * RequesttoPay.
     *
     */
    public function testRequesttoPay()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for requesttoPayDeliveryNotification
     *
     * RequesttoPayDeliveryNotification.
     *
     */
    public function testRequesttoPayDeliveryNotification()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for requesttoPayTransactionStatus
     *
     * RequesttoPayTransactionStatus.
     *
     */
    public function testRequesttoPayTransactionStatus()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for validateAccountHolderStatus
     *
     * ValidateAccountHolderStatus.
     *
     */
    public function testValidateAccountHolderStatus()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
